name: SMARTS CD PyPI

on:
  schedule:
    - cron: '30 8 * * *'

jobs:
  package:
    runs-on: ubuntu-20.04
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        repository: huawei-noah/SMARTS
        path: '.'
    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.8"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install wheel==0.38.4
        pip install .[dev,doc]
        pip install -r requirements.txt
        pip install twine
    - name: Build SMARTS binary wheel
      run: |
        make wheel
    - name: Twine check 
      run: |
        twine check dist/*    
    - name: Publish SMARTS to PyPI
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        user: __token__
        password: ${{ secrets.PYPI_API_TOKEN }}
