name: SMARTS CD PyPI

on:
  schedule:
    - cron: '0 10 * * *'

jobs:
  package:
    runs-on: ubuntu-20.04
    container: ghcr.io/smarts-project/smarts:v0.6.1-minimal
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        repository: huawei-noah/SMARTS
        path: '.'
    - name: Setup Python
      uses: actions/setup-python@v4
      id: cp38
      with:
        python-version: "3.8"
    - name: Install Enchant
      run: |
        apt-get update --fix-missing
        apt-get install -y libenchant-dev
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install wheel==0.38.4
        pip install .[all]
        pip install -r requirements.txt
        pip install twine
    - name: Build SMARTS binary wheel
      run: |
        make wheel
    - name: Twine check
      id: twine_check
      run: |
        twine check --strict dist/*    
    - name: Publish SMARTS to PyPI
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        user: __token__
        password: ${{ secrets.PYPI_API_TOKEN }}
