name: readthedocs-auto-build

on: 
  schedule:
    - cron: '0 23 * * 1'
      # Runs at 11.00pm, UTC, every Monday
  push:
    branches:
      - develop
  release:
    branches:
      - develop
  merge_group:
    branches:
      - develop

jobs:
  readthedocs-auto-build:
    runs-on: ubuntu-latest
    steps:
     - name: build_docs
       run: |
        curl -X POST -d "branches=develop" -d "token=${{ secrets.RTDS_WEBHOOK_TOKEN }}" ${{ secrets.RTDS_WEBHOOK_URL }}