name: readthedocs-auto-build

on: 
  schedule:
    - cron: '0 23 * * 1'
      # Runs at 11.00pm, UTC, every Monday
  push:
    branches:
      - master
  release:
    branches:
      - master
  merge_group:
    branches:
      - master

jobs:
  readthedocs-auto-build:
    runs-on: ubuntu-latest
    steps:
     - name: Install Enchant
       run: |
        apt-get update --fix-missing
        apt-get install -y libenchant-dev
     - name: build_docs
       run: |
        curl -X POST -d "branches=master" -d "token=${{ secrets.RTDS_WEBHOOK_TOKEN }}" ${{ secrets.RTDS_WEBHOOK_URL }}
